// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package httpapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AppSourceKind.
const (
	ContainerImage AppSourceKind = "containerImage"
	GitRepo        AppSourceKind = "gitRepo"
	HelmHttp       AppSourceKind = "helmHttp"
	HelmOci        AppSourceKind = "helmOci"
	KubeManifest   AppSourceKind = "kubeManifest"
	VelaTemplate   AppSourceKind = "velaTemplate"
)

// Defines values for AppStatusPhase.
const (
	AppStatusPhaseDeploying AppStatusPhase = "Deploying"
	AppStatusPhaseFailed    AppStatusPhase = "Failed"
	AppStatusPhasePending   AppStatusPhase = "Pending"
	AppStatusPhaseRunning   AppStatusPhase = "Running"
	AppStatusPhaseSuspended AppStatusPhase = "Suspended"
)

// Defines values for CatalogEntityType.
const (
	Component CatalogEntityType = "component"
	Trait     CatalogEntityType = "trait"
	Workflow  CatalogEntityType = "workflow"
)

// Defines values for CatalogItemScope.
const (
	CatalogItemScopeGlobal CatalogItemScope = "global"
	CatalogItemScopeTenant CatalogItemScope = "tenant"
)

// Defines values for ConditionStatus.
const (
	False   ConditionStatus = "false"
	True    ConditionStatus = "true"
	Unknown ConditionStatus = "Unknown"
)

// Defines values for ProjectAccessMembersRole.
const (
	ProjectAccessMembersRoleProjectDev  ProjectAccessMembersRole = "projectDev"
	ProjectAccessMembersRoleReadOnly    ProjectAccessMembersRole = "readOnly"
	ProjectAccessMembersRoleTenantOwner ProjectAccessMembersRole = "tenantOwner"
)

// Defines values for TokenRequestRoles.
const (
	TokenRequestRolesAdmin       TokenRequestRoles = "admin"
	TokenRequestRolesOps         TokenRequestRoles = "ops"
	TokenRequestRolesProjectDev  TokenRequestRoles = "projectDev"
	TokenRequestRolesReadOnly    TokenRequestRoles = "readOnly"
	TokenRequestRolesTenantOwner TokenRequestRoles = "tenantOwner"
)

// Defines values for WorkflowRunStatus.
const (
	WorkflowRunStatusFailed    WorkflowRunStatus = "Failed"
	WorkflowRunStatusRunning   WorkflowRunStatus = "Running"
	WorkflowRunStatusSucceeded WorkflowRunStatus = "Succeeded"
)

// Defines values for GetApiV1CatalogParamsScope.
const (
	GetApiV1CatalogParamsScopeGlobal GetApiV1CatalogParamsScope = "global"
	GetApiV1CatalogParamsScopeTenant GetApiV1CatalogParamsScope = "tenant"
)

// Defines values for GetApiV1ProjectsPUsageParamsRange.
const (
	GetApiV1ProjectsPUsageParamsRangeN1h  GetApiV1ProjectsPUsageParamsRange = "1h"
	GetApiV1ProjectsPUsageParamsRangeN24h GetApiV1ProjectsPUsageParamsRange = "24h"
	GetApiV1ProjectsPUsageParamsRangeN30d GetApiV1ProjectsPUsageParamsRange = "30d"
	GetApiV1ProjectsPUsageParamsRangeN7d  GetApiV1ProjectsPUsageParamsRange = "7d"
)

// Defines values for PostApiV1TenantsTKubeconfigJSONBodyRole.
const (
	ProjectDev  PostApiV1TenantsTKubeconfigJSONBodyRole = "projectDev"
	ReadOnly    PostApiV1TenantsTKubeconfigJSONBodyRole = "readOnly"
	TenantOwner PostApiV1TenantsTKubeconfigJSONBodyRole = "tenantOwner"
)

// Defines values for GetApiV1TenantsTUsageParamsRange.
const (
	GetApiV1TenantsTUsageParamsRangeN1h  GetApiV1TenantsTUsageParamsRange = "1h"
	GetApiV1TenantsTUsageParamsRangeN24h GetApiV1TenantsTUsageParamsRange = "24h"
	GetApiV1TenantsTUsageParamsRangeN30d GetApiV1TenantsTUsageParamsRange = "30d"
	GetApiV1TenantsTUsageParamsRangeN7d  GetApiV1TenantsTUsageParamsRange = "7d"
)

// App defines model for App.
type App struct {
	Components  *[]map[string]interface{} `json:"components,omitempty"`
	CreatedAt   *time.Time                `json:"createdAt,omitempty"`
	Description *string                   `json:"description,omitempty"`

	// Id Stable unique identifier
	Id       *openapi_types.UUID       `json:"id,omitempty"`
	Name     string                    `json:"name"`
	Policies *[]map[string]interface{} `json:"policies,omitempty"`
	Spec     *AppSpec                  `json:"spec,omitempty"`
	Traits   *[]map[string]interface{} `json:"traits,omitempty"`
}

// AppCatalogRef defines model for AppCatalogRef.
type AppCatalogRef struct {
	Name    string  `json:"name"`
	Version *string `json:"version,omitempty"`
}

// AppDiff defines model for AppDiff.
type AppDiff struct {
	Changes *[]map[string]interface{} `json:"changes,omitempty"`
	From    *int                      `json:"from,omitempty"`
	To      *int                      `json:"to,omitempty"`
}

// AppRevision defines model for AppRevision.
type AppRevision struct {
	CreatedAt *time.Time              `json:"createdAt,omitempty"`
	Revision  *int                    `json:"revision,omitempty"`
	Summary   *map[string]interface{} `json:"summary,omitempty"`
}

// AppSource defines model for AppSource.
type AppSource struct {
	CatalogRef     *AppCatalogRef           `json:"catalogRef,omitempty"`
	ContainerImage *AppSourceContainerImage `json:"containerImage,omitempty"`
	GitRepo        *AppSourceGitRepo        `json:"gitRepo,omitempty"`
	HelmHttp       *AppSourceHelmHttp       `json:"helmHttp,omitempty"`
	HelmOci        *AppSourceHelmOci        `json:"helmOci,omitempty"`
	Kind           AppSourceKind            `json:"kind"`
	KubeManifest   *AppSourceKubeManifest   `json:"kubeManifest,omitempty"`
	VelaTemplate   *AppSourceVelaTemplate   `json:"velaTemplate,omitempty"`
}

// AppSourceKind defines model for AppSource.Kind.
type AppSourceKind string

// AppSourceContainerImage defines model for AppSourceContainerImage.
type AppSourceContainerImage struct {
	CredentialsSecretRef *SecretRef          `json:"credentialsSecretRef,omitempty"`
	Env                  *[]AppSourceEnvVar  `json:"env,omitempty"`
	Image                *string             `json:"image,omitempty"`
	Ports                *[]int              `json:"ports,omitempty"`
	Resources            *AppSourceResources `json:"resources,omitempty"`
	Tag                  *string             `json:"tag,omitempty"`
}

// AppSourceEnvVar defines model for AppSourceEnvVar.
type AppSourceEnvVar struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// AppSourceGitRepo defines model for AppSourceGitRepo.
type AppSourceGitRepo struct {
	CredentialsSecretRef *SecretRef `json:"credentialsSecretRef,omitempty"`
	Path                 *string    `json:"path,omitempty"`
	Revision             *string    `json:"revision,omitempty"`
	Url                  *string    `json:"url,omitempty"`
}

// AppSourceHelmHttp defines model for AppSourceHelmHttp.
type AppSourceHelmHttp struct {
	Chart                *string                 `json:"chart,omitempty"`
	CredentialsSecretRef *SecretRef              `json:"credentialsSecretRef,omitempty"`
	RepoUrl              *string                 `json:"repoUrl,omitempty"`
	Values               *map[string]interface{} `json:"values,omitempty"`
	Version              *string                 `json:"version,omitempty"`
}

// AppSourceHelmOci defines model for AppSourceHelmOci.
type AppSourceHelmOci struct {
	Chart                *string                 `json:"chart,omitempty"`
	CredentialsSecretRef *SecretRef              `json:"credentialsSecretRef,omitempty"`
	Registry             *string                 `json:"registry,omitempty"`
	Values               *map[string]interface{} `json:"values,omitempty"`
	Version              *string                 `json:"version,omitempty"`
}

// AppSourceKubeManifest defines model for AppSourceKubeManifest.
type AppSourceKubeManifest struct {
	Manifest *map[string]interface{} `json:"manifest,omitempty"`
}

// AppSourceResources defines model for AppSourceResources.
type AppSourceResources struct {
	Limits   *map[string]string `json:"limits,omitempty"`
	Requests *map[string]string `json:"requests,omitempty"`
}

// AppSourceVelaTemplate defines model for AppSourceVelaTemplate.
type AppSourceVelaTemplate struct {
	CredentialsSecretRef *SecretRef              `json:"credentialsSecretRef,omitempty"`
	Parameters           *map[string]interface{} `json:"parameters,omitempty"`
	Template             *string                 `json:"template,omitempty"`
	Version              *string                 `json:"version,omitempty"`
}

// AppSpec defines model for AppSpec.
type AppSpec struct {
	CatalogItemId    *openapi_types.UUID     `json:"catalogItemId,omitempty"`
	CatalogOverrides *map[string]interface{} `json:"catalogOverrides,omitempty"`
	CatalogVersion   *string                 `json:"catalogVersion,omitempty"`
	Source           *AppSource              `json:"source,omitempty"`
}

// AppStatus defines model for AppStatus.
type AppStatus struct {
	Conditions  *[]Condition    `json:"conditions,omitempty"`
	Healthy     *bool           `json:"healthy,omitempty"`
	LastUpdated *time.Time      `json:"lastUpdated,omitempty"`
	Phase       *AppStatusPhase `json:"phase,omitempty"`
}

// AppStatusPhase defines model for AppStatus.Phase.
type AppStatusPhase string

// CatalogEntity defines model for CatalogEntity.
type CatalogEntity struct {
	Description *string                 `json:"description,omitempty"`
	Name        *string                 `json:"name,omitempty"`
	Schema      *map[string]interface{} `json:"schema,omitempty"`
	Type        *CatalogEntityType      `json:"type,omitempty"`
}

// CatalogEntityType defines model for CatalogEntity.Type.
type CatalogEntityType string

// CatalogInstall defines model for CatalogInstall.
type CatalogInstall struct {
	Slug string `json:"slug"`

	// Source Optional overrides merged into the catalog item source.
	Source *map[string]interface{} `json:"source,omitempty"`
}

// CatalogItem defines model for CatalogItem.
type CatalogItem struct {
	Category    *string                `json:"category,omitempty"`
	CreatedAt   *time.Time             `json:"createdAt,omitempty"`
	Description *string                `json:"description,omitempty"`
	Icon        *string                `json:"icon,omitempty"`
	Id          openapi_types.UUID     `json:"id"`
	Name        string                 `json:"name"`
	Scope       CatalogItemScope       `json:"scope"`
	Slug        string                 `json:"slug"`
	Source      map[string]interface{} `json:"source"`
	TenantId    *openapi_types.UUID    `json:"tenantId"`
	Version     *string                `json:"version,omitempty"`
}

// CatalogItemScope defines model for CatalogItem.Scope.
type CatalogItemScope string

// Cluster defines model for Cluster.
type Cluster struct {
	Conditions  *[]Condition `json:"conditions,omitempty"`
	CreatedAt   *time.Time   `json:"createdAt,omitempty"`
	DisplayName *string      `json:"displayName,omitempty"`

	// Id Stable unique identifier
	Id     *openapi_types.UUID `json:"id,omitempty"`
	Labels *map[string]string  `json:"labels,omitempty"`
	Name   string              `json:"name"`
}

// ClusterCapabilities defines model for ClusterCapabilities.
type ClusterCapabilities struct {
	Proxy   *bool `json:"proxy,omitempty"`
	Tenancy *bool `json:"tenancy,omitempty"`
	Vela    *bool `json:"vela,omitempty"`
}

// ClusterRegistration defines model for ClusterRegistration.
type ClusterRegistration struct {
	// CapsuleProxyCa Optional CA bundle for capsule-proxy, base64-encoded and used as certificate-authority-data in issued kubeconfigs.
	CapsuleProxyCa *[]byte `json:"capsuleProxyCa,omitempty"`

	// CapsuleProxyUrl HTTPS URL for capsule-proxy that will be used in all kubeconfigs issued for this cluster.
	CapsuleProxyUrl string             `json:"capsuleProxyUrl"`
	Kubeconfig      []byte             `json:"kubeconfig"`
	Labels          *map[string]string `json:"labels,omitempty"`
	Name            string             `json:"name"`
}

// Condition defines model for Condition.
type Condition struct {
	LastTransitionTime *time.Time       `json:"lastTransitionTime,omitempty"`
	Message            *string          `json:"message,omitempty"`
	Reason             *string          `json:"reason,omitempty"`
	Status             *ConditionStatus `json:"status,omitempty"`
	Type               *string          `json:"type,omitempty"`
}

// ConditionStatus defines model for Condition.Status.
type ConditionStatus string

// Error defines model for Error.
type Error struct {
	// Code KN-400, KN-401, KN-403, KN-404, KN-409, KN-422, KN-500
	Code    string       `json:"code"`
	Details *interface{} `json:"details,omitempty"`
	Message string       `json:"message"`
}

// KubeconfigResponse defines model for KubeconfigResponse.
type KubeconfigResponse struct {
	// ExpiresAt Omitted or null when TTL is unlimited.
	ExpiresAt  *time.Time `json:"expiresAt"`
	Kubeconfig *[]byte    `json:"kubeconfig,omitempty"`
}

// LogLine defines model for LogLine.
type LogLine struct {
	Component *string    `json:"component,omitempty"`
	Message   *string    `json:"message,omitempty"`
	Ts        *time.Time `json:"ts,omitempty"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Roles   *[]string `json:"roles,omitempty"`
	Subject *string   `json:"subject,omitempty"`
}

// Plan defines model for Plan.
type Plan struct {
	Description  *string            `json:"description,omitempty"`
	Name         string             `json:"name"`
	Policysets   *[]string          `json:"policysets,omitempty"`
	TenantQuotas *map[string]string `json:"tenantQuotas,omitempty"`
}

// PolicySet defines model for PolicySet.
type PolicySet struct {
	AttachedTo *[]struct {
		Project *string `json:"project,omitempty"`
		Tenant  *string `json:"tenant,omitempty"`
	} `json:"attachedTo,omitempty"`
	Description *string                   `json:"description,omitempty"`
	Name        string                    `json:"name"`
	Rules       *[]map[string]interface{} `json:"rules,omitempty"`
}

// Project defines model for Project.
type Project struct {
	Annotations *map[string]string `json:"annotations,omitempty"`
	CreatedAt   *time.Time         `json:"createdAt,omitempty"`

	// Id Stable unique identifier
	Id     *openapi_types.UUID `json:"id,omitempty"`
	Labels *map[string]string  `json:"labels,omitempty"`
	Name   string              `json:"name"`
}

// ProjectAccess defines model for ProjectAccess.
type ProjectAccess struct {
	Members *[]struct {
		Role    ProjectAccessMembersRole `json:"role"`
		Subject string                   `json:"subject"`
	} `json:"members,omitempty"`
}

// ProjectAccessMembersRole defines model for ProjectAccess.Members.Role.
type ProjectAccessMembersRole string

// Sandbox defines model for Sandbox.
type Sandbox struct {
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt"`

	// Id Stable unique identifier
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Kubeconfig *[]byte             `json:"kubeconfig,omitempty"`
	Name       *string             `json:"name,omitempty"`
	Namespace  *string             `json:"namespace,omitempty"`
	Tenant     *string             `json:"tenant,omitempty"`
}

// SandboxCreate defines model for SandboxCreate.
type SandboxCreate struct {
	Name       string `json:"name"`
	TtlSeconds *int   `json:"ttlSeconds,omitempty"`
}

// SecretRef defines model for SecretRef.
type SecretRef struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	Annotations *map[string]string `json:"annotations,omitempty"`
	CreatedAt   *time.Time         `json:"createdAt,omitempty"`

	// Id Stable unique identifier
	Id     *openapi_types.UUID `json:"id,omitempty"`
	Labels *map[string]string  `json:"labels,omitempty"`
	Name   string              `json:"name"`
	Owners *[]string           `json:"owners,omitempty"`

	// Plan Optional tenant plan name (e.g. baseline, gold). When omitted on creation the server may apply a default baseline plan when available.
	Plan *string `json:"plan,omitempty"`
}

// TenantSummary defines model for TenantSummary.
type TenantSummary struct {
	Namespaces *[]string `json:"namespaces,omitempty"`

	// Plan Optional tenant plan name applied to this tenant
	Plan   *string            `json:"plan,omitempty"`
	Quotas *map[string]string `json:"quotas,omitempty"`
	Usages *map[string]string `json:"usages,omitempty"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Roles      *[]TokenRequestRoles `json:"roles,omitempty"`
	Subject    string               `json:"subject"`
	TtlSeconds *int                 `json:"ttlSeconds,omitempty"`
}

// TokenRequestRoles defines model for TokenRequest.Roles.
type TokenRequestRoles string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Token     *string    `json:"token,omitempty"`
}

// UsageReport defines model for UsageReport.
type UsageReport struct {
	Cpu    *string `json:"cpu,omitempty"`
	Memory *string `json:"memory,omitempty"`
	Pods   *int    `json:"pods,omitempty"`
	Window *string `json:"window,omitempty"`
}

// WorkflowRun defines model for WorkflowRun.
type WorkflowRun struct {
	FinishedAt *time.Time         `json:"finishedAt"`
	Id         *string            `json:"id,omitempty"`
	StartedAt  *time.Time         `json:"startedAt,omitempty"`
	Status     *WorkflowRunStatus `json:"status,omitempty"`
}

// WorkflowRunStatus defines model for WorkflowRun.Status.
type WorkflowRunStatus string

// AppParam defines model for AppParam.
type AppParam = openapi_types.UUID

// ClusterParam defines model for ClusterParam.
type ClusterParam = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// LabelSelector defines model for LabelSelector.
type LabelSelector = string

// Limit defines model for Limit.
type Limit = int

// OwnerFilter defines model for OwnerFilter.
type OwnerFilter = string

// ProjectParam defines model for ProjectParam.
type ProjectParam = openapi_types.UUID

// TenantParam defines model for TenantParam.
type TenantParam = openapi_types.UUID

// GetApiV1CatalogParams defines parameters for GetApiV1Catalog.
type GetApiV1CatalogParams struct {
	Scope *GetApiV1CatalogParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// TenantId Required when scope=tenant.
	TenantId *openapi_types.UUID `form:"tenantId,omitempty" json:"tenantId,omitempty"`
}

// GetApiV1CatalogParamsScope defines parameters for GetApiV1Catalog.
type GetApiV1CatalogParamsScope string

// GetApiV1ClustersParams defines parameters for GetApiV1Clusters.
type GetApiV1ClustersParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor        *Cursor        `form:"cursor,omitempty" json:"cursor,omitempty"`
	LabelSelector *LabelSelector `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
}

// GetApiV1ClustersCTenantsParams defines parameters for GetApiV1ClustersCTenants.
type GetApiV1ClustersCTenantsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor        *Cursor        `form:"cursor,omitempty" json:"cursor,omitempty"`
	LabelSelector *LabelSelector `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
	Owner         *OwnerFilter   `form:"owner,omitempty" json:"owner,omitempty"`
}

// PostApiV1ClustersCTenantsParams defines parameters for PostApiV1ClustersCTenants.
type PostApiV1ClustersCTenantsParams struct {
	Limit         *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor        *Cursor        `form:"cursor,omitempty" json:"cursor,omitempty"`
	LabelSelector *LabelSelector `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`
	Owner         *OwnerFilter   `form:"owner,omitempty" json:"owner,omitempty"`
}

// PutApiV1ClustersCTenantsTLimitsJSONBody defines parameters for PutApiV1ClustersCTenantsTLimits.
type PutApiV1ClustersCTenantsTLimitsJSONBody map[string]string

// PutApiV1ClustersCTenantsTNetworkPoliciesJSONBody defines parameters for PutApiV1ClustersCTenantsTNetworkPolicies.
type PutApiV1ClustersCTenantsTNetworkPoliciesJSONBody = map[string]interface{}

// PutApiV1ClustersCTenantsTOwnersJSONBody defines parameters for PutApiV1ClustersCTenantsTOwners.
type PutApiV1ClustersCTenantsTOwnersJSONBody struct {
	Owners *[]string `json:"owners,omitempty"`
}

// GetApiV1ClustersCTenantsTProjectsPAppsParams defines parameters for GetApiV1ClustersCTenantsTProjectsPApps.
type GetApiV1ClustersCTenantsTProjectsPAppsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// PostApiV1ClustersCTenantsTProjectsPAppsAImageUpdateJSONBody defines parameters for PostApiV1ClustersCTenantsTProjectsPAppsAImageUpdate.
type PostApiV1ClustersCTenantsTProjectsPAppsAImageUpdateJSONBody struct {
	Component string  `json:"component"`
	Image     string  `json:"image"`
	Tag       *string `json:"tag,omitempty"`
}

// GetApiV1ClustersCTenantsTProjectsPAppsALogsComponentParams defines parameters for GetApiV1ClustersCTenantsTProjectsPAppsALogsComponent.
type GetApiV1ClustersCTenantsTProjectsPAppsALogsComponentParams struct {
	Follow       *bool `form:"follow,omitempty" json:"follow,omitempty"`
	Tail         *int  `form:"tail,omitempty" json:"tail,omitempty"`
	SinceSeconds *int  `form:"sinceSeconds,omitempty" json:"sinceSeconds,omitempty"`
}

// PutApiV1ClustersCTenantsTProjectsPAppsAPoliciesJSONBody defines parameters for PutApiV1ClustersCTenantsTProjectsPAppsAPolicies.
type PutApiV1ClustersCTenantsTProjectsPAppsAPoliciesJSONBody = []map[string]interface{}

// PutApiV1ClustersCTenantsTProjectsPAppsATraitsJSONBody defines parameters for PutApiV1ClustersCTenantsTProjectsPAppsATraits.
type PutApiV1ClustersCTenantsTProjectsPAppsATraitsJSONBody = []map[string]interface{}

// PostApiV1ClustersCTenantsTProjectsPAppsAWorkflowRunJSONBody defines parameters for PostApiV1ClustersCTenantsTProjectsPAppsAWorkflowRun.
type PostApiV1ClustersCTenantsTProjectsPAppsAWorkflowRunJSONBody struct {
	Steps *[]string `json:"steps,omitempty"`
}

// GetApiV1ClustersCTenantsTProjectsPAppsAWorkflowRunsParams defines parameters for GetApiV1ClustersCTenantsTProjectsPAppsAWorkflowRuns.
type GetApiV1ClustersCTenantsTProjectsPAppsAWorkflowRunsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// PostApiV1ClustersCTenantsTProjectsPAppsARollbackJSONBody defines parameters for PostApiV1ClustersCTenantsTProjectsPAppsARollback.
type PostApiV1ClustersCTenantsTProjectsPAppsARollbackJSONBody struct {
	ToRevision *int `json:"toRevision,omitempty"`
}

// PutApiV1ClustersCTenantsTQuotasJSONBody defines parameters for PutApiV1ClustersCTenantsTQuotas.
type PutApiV1ClustersCTenantsTQuotasJSONBody map[string]string

// GetApiV1ProjectsPUsageParams defines parameters for GetApiV1ProjectsPUsage.
type GetApiV1ProjectsPUsageParams struct {
	Range   *GetApiV1ProjectsPUsageParamsRange `form:"range,omitempty" json:"range,omitempty"`
	Cluster *string                            `form:"cluster,omitempty" json:"cluster,omitempty"`
}

// GetApiV1ProjectsPUsageParamsRange defines parameters for GetApiV1ProjectsPUsage.
type GetApiV1ProjectsPUsageParamsRange string

// PostApiV1TenantsTKubeconfigJSONBody defines parameters for PostApiV1TenantsTKubeconfig.
type PostApiV1TenantsTKubeconfigJSONBody struct {
	// Project Optional project name for a namespace-scoped kubeconfig. Required when role is projectDev.
	Project *string `json:"project,omitempty"`

	// Role Logical role; actual RBAC is enforced by the access proxy.
	Role *PostApiV1TenantsTKubeconfigJSONBodyRole `json:"role,omitempty"`

	// TtlSeconds 0 or omitted means unlimited TTL; otherwise seconds until expiry.
	TtlSeconds *int `json:"ttlSeconds,omitempty"`
}

// PostApiV1TenantsTKubeconfigJSONBodyRole defines parameters for PostApiV1TenantsTKubeconfig.
type PostApiV1TenantsTKubeconfigJSONBodyRole string

// PutApiV1TenantsTPlanJSONBody defines parameters for PutApiV1TenantsTPlan.
type PutApiV1TenantsTPlanJSONBody struct {
	Name string `json:"name"`
}

// GetApiV1TenantsTUsageParams defines parameters for GetApiV1TenantsTUsage.
type GetApiV1TenantsTUsageParams struct {
	Range   *GetApiV1TenantsTUsageParamsRange `form:"range,omitempty" json:"range,omitempty"`
	Cluster *string                           `form:"cluster,omitempty" json:"cluster,omitempty"`
}

// GetApiV1TenantsTUsageParamsRange defines parameters for GetApiV1TenantsTUsage.
type GetApiV1TenantsTUsageParamsRange string

// PostApiV1ClustersJSONRequestBody defines body for PostApiV1Clusters for application/json ContentType.
type PostApiV1ClustersJSONRequestBody = ClusterRegistration

// PostApiV1ClustersCTenantsJSONRequestBody defines body for PostApiV1ClustersCTenants for application/json ContentType.
type PostApiV1ClustersCTenantsJSONRequestBody = Tenant

// PutApiV1ClustersCTenantsTLimitsJSONRequestBody defines body for PutApiV1ClustersCTenantsTLimits for application/json ContentType.
type PutApiV1ClustersCTenantsTLimitsJSONRequestBody PutApiV1ClustersCTenantsTLimitsJSONBody

// PutApiV1ClustersCTenantsTNetworkPoliciesJSONRequestBody defines body for PutApiV1ClustersCTenantsTNetworkPolicies for application/json ContentType.
type PutApiV1ClustersCTenantsTNetworkPoliciesJSONRequestBody = PutApiV1ClustersCTenantsTNetworkPoliciesJSONBody

// PutApiV1ClustersCTenantsTOwnersJSONRequestBody defines body for PutApiV1ClustersCTenantsTOwners for application/json ContentType.
type PutApiV1ClustersCTenantsTOwnersJSONRequestBody PutApiV1ClustersCTenantsTOwnersJSONBody

// PostApiV1ClustersCTenantsTPolicysetsJSONRequestBody defines body for PostApiV1ClustersCTenantsTPolicysets for application/json ContentType.
type PostApiV1ClustersCTenantsTPolicysetsJSONRequestBody = PolicySet

// PutApiV1ClustersCTenantsTPolicysetsNameJSONRequestBody defines body for PutApiV1ClustersCTenantsTPolicysetsName for application/json ContentType.
type PutApiV1ClustersCTenantsTPolicysetsNameJSONRequestBody = PolicySet

// PostApiV1ClustersCTenantsTProjectsJSONRequestBody defines body for PostApiV1ClustersCTenantsTProjects for application/json ContentType.
type PostApiV1ClustersCTenantsTProjectsJSONRequestBody = Project

// PutApiV1ClustersCTenantsTProjectsPJSONRequestBody defines body for PutApiV1ClustersCTenantsTProjectsP for application/json ContentType.
type PutApiV1ClustersCTenantsTProjectsPJSONRequestBody = Project

// PutApiV1ClustersCTenantsTProjectsPAccessJSONRequestBody defines body for PutApiV1ClustersCTenantsTProjectsPAccess for application/json ContentType.
type PutApiV1ClustersCTenantsTProjectsPAccessJSONRequestBody = ProjectAccess

// PostApiV1ClustersCTenantsTProjectsPAppsJSONRequestBody defines body for PostApiV1ClustersCTenantsTProjectsPApps for application/json ContentType.
type PostApiV1ClustersCTenantsTProjectsPAppsJSONRequestBody = App

// PutApiV1ClustersCTenantsTProjectsPAppsAJSONRequestBody defines body for PutApiV1ClustersCTenantsTProjectsPAppsA for application/json ContentType.
type PutApiV1ClustersCTenantsTProjectsPAppsAJSONRequestBody = App

// PostApiV1ClustersCTenantsTProjectsPAppsAImageUpdateJSONRequestBody defines body for PostApiV1ClustersCTenantsTProjectsPAppsAImageUpdate for application/json ContentType.
type PostApiV1ClustersCTenantsTProjectsPAppsAImageUpdateJSONRequestBody PostApiV1ClustersCTenantsTProjectsPAppsAImageUpdateJSONBody

// PutApiV1ClustersCTenantsTProjectsPAppsAPoliciesJSONRequestBody defines body for PutApiV1ClustersCTenantsTProjectsPAppsAPolicies for application/json ContentType.
type PutApiV1ClustersCTenantsTProjectsPAppsAPoliciesJSONRequestBody = PutApiV1ClustersCTenantsTProjectsPAppsAPoliciesJSONBody

// PutApiV1ClustersCTenantsTProjectsPAppsATraitsJSONRequestBody defines body for PutApiV1ClustersCTenantsTProjectsPAppsATraits for application/json ContentType.
type PutApiV1ClustersCTenantsTProjectsPAppsATraitsJSONRequestBody = PutApiV1ClustersCTenantsTProjectsPAppsATraitsJSONBody

// PostApiV1ClustersCTenantsTProjectsPAppsAWorkflowRunJSONRequestBody defines body for PostApiV1ClustersCTenantsTProjectsPAppsAWorkflowRun for application/json ContentType.
type PostApiV1ClustersCTenantsTProjectsPAppsAWorkflowRunJSONRequestBody PostApiV1ClustersCTenantsTProjectsPAppsAWorkflowRunJSONBody

// PostApiV1ClustersCTenantsTProjectsPAppsARollbackJSONRequestBody defines body for PostApiV1ClustersCTenantsTProjectsPAppsARollback for application/json ContentType.
type PostApiV1ClustersCTenantsTProjectsPAppsARollbackJSONRequestBody PostApiV1ClustersCTenantsTProjectsPAppsARollbackJSONBody

// PostApiV1ClustersCTenantsTProjectsPCatalogInstallJSONRequestBody defines body for PostApiV1ClustersCTenantsTProjectsPCatalogInstall for application/json ContentType.
type PostApiV1ClustersCTenantsTProjectsPCatalogInstallJSONRequestBody = CatalogInstall

// PutApiV1ClustersCTenantsTQuotasJSONRequestBody defines body for PutApiV1ClustersCTenantsTQuotas for application/json ContentType.
type PutApiV1ClustersCTenantsTQuotasJSONRequestBody PutApiV1ClustersCTenantsTQuotasJSONBody

// PostApiV1TenantsTKubeconfigJSONRequestBody defines body for PostApiV1TenantsTKubeconfig for application/json ContentType.
type PostApiV1TenantsTKubeconfigJSONRequestBody PostApiV1TenantsTKubeconfigJSONBody

// PutApiV1TenantsTPlanJSONRequestBody defines body for PutApiV1TenantsTPlan for application/json ContentType.
type PutApiV1TenantsTPlanJSONRequestBody PutApiV1TenantsTPlanJSONBody

// PostApiV1TenantsTSandboxJSONRequestBody defines body for PostApiV1TenantsTSandbox for application/json ContentType.
type PostApiV1TenantsTSandboxJSONRequestBody = SandboxCreate

// PostApiV1TokensJSONRequestBody defines body for PostApiV1Tokens for application/json ContentType.
type PostApiV1TokensJSONRequestBody = TokenRequest
